Adding silencer dependency as a workaround for DottyDoc error on Scala 3.2.2, error was:
  [error] -- Error: core/shared/src/main/scala/zio/stm/ZTRef.scala:529:4 -----------------
  [error] undefined: new com.github.ghik.silencer.silent # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class ghik)),object silencer),silent),<init>) at readTasty

Arising from linking to [[zio.stm.ZTRef.UnifiedSyntax#modify]] method which has a silencer
annotation on it.